version: "3.9"

services:
  page-analyzer:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: page-analyzer
    restart: unless-stopped
    volumes:
      - .:/page-analyzer
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "poetry run gunicorn -w 5 -b 0.0.0.0:8000 page_analyzer:app"

  db:
    image: postgres
    container_name: page-analyzer_db
    restart: unless-stopped
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    env_file:
      - .env
