version: "3.9"

services:
  page-analyzer:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: page-analyzer
    restart: unless-stopped
    volumes:
      - .:/page-analyzer
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: sh -c "poetry run gunicorn -w 5 -b 0.0.0.0:8000 page_analyzer:app"

  db:
    image: postgres
    container_name: page-analyzer_db
    restart: unless-stopped
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    env_file:
      - .env

  redis:
    image: redis:5.0.5
    container_name: redis

  celery:
    container_name: celery
    user: nobody
    build: .
    env_file:
      - .env
    command: "celery -A page_analyzer.celery_config.celery_app worker --loglevel=info"
    depends_on:
      - redis
      - db
    volumes:
        - ./celery/app:/app

  celery_beat:
    container_name: celery_beat
    build: .
    env_file:
      - .env
    command: "celery -A page_analyzer.celery_config.celery_app beat --loglevel=info"
    depends_on:
      - redis
      - db
    volumes:
        - ./celery/app:/app
